spring:
  application:
    name: management

  kafka:
    bootstrapServers: kafka:9092
    consumer:
      topics:
        client: client
        courier: courier
        coords: coords
        chat: chat
        message: message
        feedback: feedback
      group-id: group1
      auto-offset-reset: earliest

url:
  yandex: https://api.routing.yandex.net/v2/distancematrix

apikey: